import React, { useEffect, useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import HomePage from "../components/HomePage";

export default function Home() {
  const [showChild, setShowChild] = useState(false);
  useEffect(() => {
    setShowChild(true);
  }, []);

  if (!showChild) {
    return <p style={{ textAlign: "center" }}>Loading...</p>;
  }
  if (typeof window === "undefined") {
    return <p style={{ textAlign: "center" }}>Loading...</p>;
  } else {
    return (
      <div>
        <Head>
          <title>Tesla Clone</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <HomePage />
      </div>
    );
  }
}
